### ISSUE TITLE
Aside tabs in drupal admin

### ISSUE THREAD

**Issue by rob-bar** [Crosscheck/Powerplant#5]
https://github.com/Crosscheck/Ocelot/issues/23.
This should contain only php, scss and js:
This is legacy code, and can be done much better, but this serves as a basic example: 
scss:

``` scss
html body.admin-menu {
  @include breakpoint($b-tablet) {
    .open-tabs {
      margin-top: 60px;
    }
  }
}

html body.admin-menu-with-shortcuts {
  @include breakpoint($b-tablet) {
    .open-tabs {
      margin-top: 95px;
    }
  }
}

html body.body-tabs-open {
  margin-left: 250px;

  #admin-menu {
    left: 250px;
  }

  .open-tabs {
    @include breakpoint($b-tablet) {
      left: 270px;

    }
  }
}

.open-tabs {
  z-index: 190;
  background-color: $c-red;
  @include corner(fixed, "tl");
  @include circle(50px);
  color: $c-white;
  padding: 18px 17px;
  @include box-shadow(0 0 0 rgba($c-black, 0));

  &:hover {
    @include scale(.9);
    @include box-shadow(2px 2px 3px rgba($c-black, .3));

    i {
      @include scale(1.3);
    }
  }

  &:active,
  &:hover,
  &:focus {
    outline: 0 !important;
  }

  @include breakpoint($b-tablet) {
    left: 20px;
  }
}

.tabs {
  li {
    float: none;
  }
}

.push-tabs {
  @include ceaser-transition(all, $fast, $ease-out-expo);
  position: fixed;
  z-index: 1200;
  width: 250px;
  height: 100%;
  background-color: $c-gray-light;
  @include background-image(linear-gradient(to right, $c-gray-light 90%, rgba($c-gray-neutral, .6) 100%));
  top: 0;
  left: 0;

  &.hide {
    left: -250px;
  }

  @include breakpoint($b-tablet) {
    .hide {
      left: -250px;
    }
  }

  li {
    border-bottom: 1px solid $c-gray-medium;
    padding: 0;
    margin: 0;
    list-style-type: none;

    a {
      display: block;
      font-family: $montserrat;
      padding: rh(.8);
      text-decoration: none;
      color: $c-gray-darker;
      cursor: pointer;

      &.active {
        background-color: $c-red;
        color: $c-white;
        font-weight: 700;
        @include background-image(linear-gradient(to right, $c-red 90%, darken($c-red, 10%) 100%));

        &:hover {
          background-color: darken($c-red, 5%);
          @include background-image(linear-gradient(to right, darken($c-red, 5%) 90%, darken($c-red, 15%) 100%));
          color: $c-white;
        }
      }

      &:hover {
        background-color: $c-gray-medium;
        @include background-image(linear-gradient(to right, $c-gray-medium 90%, darken($c-gray-medium, 10%) 100%));
        color: $c-gray-darker;
        font-weight: 700;
      }
    }
  }
}

.user-tabs {
  margin: 0 0 rh(.6);

  .tabs {
    li {
      float: left;
      margin: 0 0 0 rh(.4);

      a {
        @include button-secondary();
      }

      &:first-child {
        margin: 0;
      }

      &.active {
        a {
          background: darken($c-gray-dark, 10%);

          &:hover {
            background: lighten($c-gray-dark, 10%);
          }
        }
      }
    }
  }
}

```

BehaviorJS:

``` js
    tabs: {
      attach: function (context) {
        if (helper.contextCheck(context)) {
          return;
        }

        $(".open-tabs").click(function(e) {
          e.preventDefault();
          if(! $("html body").hasClass("body-tabs-open")) {
            $(".push-tabs").removeClass("hide");
            $("html body").addClass("body-tabs-open");

            setTimeout(function() {
              $(".push-tabs").addClass("tabs-open");
            }, 100);
          } else {
            $(".push-tabs").addClass("hide");
            $("html body").removeClass("body-tabs-open");

            setTimeout(function() {
              $(".push-tabs").removeClass("tabs-open");
            }, 400);
          }
        });
      }
    },
```

php page.tpl:

``` php
<?php if ($logged_in): ?>
  <div class="push-tabs hide">
    <?php print render($tabs); ?>
  </div>
<?php endif; ?>

<?php if ($logged_in && $show_pencil): ?>
    <a href="#" class="open-tabs"><i class="fa fa-pencil"></i></a>
  <?php endif; ?>

Inside main:
<?php if (! $logged_in): ?>
        <div class="user-tabs">
          <?php print render($tabs); ?>
        </div>
      <?php endif; ?>
```
