### ISSUE TITLE
Add pager component styling

### ISSUE THREAD

**Issue by rob-bar** [Crosscheck/Powerplant#9]
related to https://github.com/Crosscheck/Ocelot/issues/102

``` scss
.pager {
  @include pie-clearfix;
  float: left;
  list-style-type: none;
  text-align: center;
  width: 100%;

  &__item {
    @include inline-block;
    color: $c-white;
    margin: rh(.2) rh(.125);

    &--current {
      background: $c-red;
      padding: rhythm(.25) rhythm(.5);
    }

    &--ellipsis {
      background: $c-gray-medium;
      padding: rhythm(.25) rhythm(.5);
    }

    a {
      background: $c-gray-dark;
      color: $c-white;
      display: block;
      padding: rhythm(.25) rhythm(.5);
      text-decoration: none;

      &:hover,
      &:focus {
        background: lighten($c-gray-dark, 10%);
      }
    }
  }
}
```
